-- DriveIntent DuckDB schema
CREATE TABLE IF NOT EXISTS cars (
    car_id VARCHAR PRIMARY KEY,
    make VARCHAR NOT NULL,
    model VARCHAR NOT NULL,
    variant VARCHAR,
    body_type VARCHAR,
    fuel_type VARCHAR,
    transmission VARCHAR,
    manufacturing_year INTEGER,
    registration_year INTEGER,
    kilometres_driven DOUBLE,
    owner_count INTEGER,
    city VARCHAR,
    state VARCHAR,
    engine_cc DOUBLE,
    claimed_mileage_kmpl DOUBLE,
    insurance_valid BOOLEAN,
    service_history_available BOOLEAN,
    accident_history BOOLEAN,
    inspection_score DOUBLE,
    exterior_score DOUBLE,
    interior_score DOUBLE,
    engine_score DOUBLE,
    tyre_score DOUBLE,
    number_of_features INTEGER,
    acquisition_price DOUBLE,
    listed_price DOUBLE,
    inventory_entry_date DATE,
    inventory_exit_date DATE,
    sold_flag BOOLEAN,
    transaction_price DOUBLE,
    days_in_inventory INTEGER,
    delivery_available BOOLEAN,
    finance_available BOOLEAN,
    model_popularity DOUBLE
);

CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR PRIMARY KEY,
    signup_date DATE,
    home_city VARCHAR,
    age_band VARCHAR,
    income_band VARCHAR,
    family_size_band VARCHAR,
    first_time_buyer_probability DOUBLE,
    preferred_body_types VARCHAR,
    preferred_makes VARCHAR,
    preferred_fuel_types VARCHAR,
    preferred_transmissions VARCHAR,
    ideal_budget DOUBLE,
    maximum_budget DOUBLE,
    ideal_emi DOUBLE,
    maximum_emi DOUBLE,
    vehicle_age_tolerance DOUBLE,
    kilometre_tolerance DOUBLE,
    quality_sensitivity DOUBLE,
    price_sensitivity DOUBLE,
    brand_loyalty DOUBLE,
    exploration_tendency DOUBLE,
    finance_interest DOUBLE,
    purchase_urgency DOUBLE
);

CREATE TABLE IF NOT EXISTS campaigns (
    campaign_id VARCHAR PRIMARY KEY,
    campaign_name VARCHAR,
    source VARCHAR,
    medium VARCHAR,
    channel VARCHAR,
    target_city VARCHAR,
    target_segment VARCHAR,
    start_date DATE,
    end_date DATE,
    daily_budget DOUBLE,
    cost_per_click DOUBLE,
    quality_multiplier DOUBLE,
    intent_multiplier DOUBLE,
    inventory_match_multiplier DOUBLE
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    session_start TIMESTAMP,
    session_end TIMESTAMP,
    campaign_id VARCHAR,
    source VARCHAR,
    medium VARCHAR,
    device_category VARCHAR,
    city VARCHAR,
    is_returning_user BOOLEAN,
    session_sequence_number INTEGER
);

CREATE TABLE IF NOT EXISTS events (
    event_id VARCHAR PRIMARY KEY,
    event_timestamp TIMESTAMP NOT NULL,
    event_date DATE NOT NULL,
    user_id VARCHAR NOT NULL,
    session_id VARCHAR NOT NULL,
    event_name VARCHAR NOT NULL,
    car_id VARCHAR,
    item_list_id VARCHAR,
    list_position INTEGER,
    search_term VARCHAR,
    filter_name VARCHAR,
    filter_value VARCHAR,
    engagement_time_seconds DOUBLE,
    page_location VARCHAR,
    source VARCHAR,
    medium VARCHAR,
    campaign_id VARCHAR,
    device_category VARCHAR,
    city VARCHAR
);

CREATE TABLE IF NOT EXISTS impressions (
    session_id VARCHAR,
    user_id VARCHAR,
    car_id VARCHAR,
    list_position INTEGER,
    examined BOOLEAN,
    clicked BOOLEAN,
    viewed_gallery BOOLEAN,
    viewed_inspection BOOLEAN,
    compared BOOLEAN,
    emi_calculated BOOLEAN,
    wishlisted BOOLEAN,
    callback BOOLEAN,
    booked BOOLEAN,
    purchased BOOLEAN,
    event_timestamp TIMESTAMP,
    campaign_id VARCHAR
);

CREATE TABLE IF NOT EXISTS recommendation_impressions (
    recommendation_id VARCHAR PRIMARY KEY,
    model_version VARCHAR NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    user_id VARCHAR NOT NULL,
    session_id VARCHAR,
    car_id VARCHAR NOT NULL,
    candidate_source VARCHAR,
    original_rank INTEGER,
    final_rank INTEGER,
    content_score DOUBLE,
    collaborative_score DOUBLE,
    session_score DOUBLE,
    ranker_score DOUBLE,
    booking_probability DOUBLE,
    sellthrough_probability DOUBLE,
    predicted_fair_price DOUBLE,
    deal_score DOUBLE,
    inventory_priority DOUBLE,
    final_score DOUBLE,
    clicked BOOLEAN,
    wishlisted BOOLEAN,
    booked BOOLEAN,
    purchased BOOLEAN
);

CREATE TABLE IF NOT EXISTS model_metrics (
    model_name VARCHAR,
    version VARCHAR,
    metric_name VARCHAR,
    metric_value DOUBLE,
    recorded_at TIMESTAMP
);
